### ISSUE TITLE
First attempt at tutorial notebook

### ISSUE THREAD

**Issue by ThomasHaine** [MaceKuailv/OceInterp#3]
Here's my first attempt at a tutorial notebook, like we had in the summer. It mainly works, but there are some strange results for some particles!
https://user-images.githubusercontent.com/44037162/201549624-c8ff0df0-eab4-4b63-b119-fcfd74dc464a.mp4

**Comment by MaceKuailv** [comment]
This is very very strange. I will push my recent changes in a minute. Let's see if this will solve this issue.

**Comment by MaceKuailv** [comment]
I ran the notebook with newer version of the code, and do not see this. I am not sure what is going on, but it seems like this is resolved. 
![image](https://user-images.githubusercontent.com/52629492/201784719-a5b4dd7b-c05a-43dc-8237-5995c2d09ac4.png)

**Comment by ThomasHaine** [comment]
Agreed. Seems to be fixed now.
