### ISSUE TITLE
`maximum iteration count reached`

### ISSUE THREAD

**Issue by ThomasHaine** [MaceKuailv/OceInterp#5]
I achieved this warning message after 1 particle was left in the Lagrangian integration for many steps. Why does this happen?  How is it handled?

**Comment by ThomasHaine** [comment]
With latest code, this is still an issue for `SPNA_Lagrangian_demo.ipynb`

**Comment by MaceKuailv** [comment]
That's pretty strange. I think I ran the exact same notebook and didn't get the error. What is the time interval between steps? I think the SPNA one is pretty short.

**Comment by MaceKuailv** [comment]
Yes, I didn't watch it run long enough. I will investigate it this weekend. Thanks for catching that.
